# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.5
  - nightly
# matrix:
#   allow_failures:
#     - julia: nightly
notifications:
  email: false
#script: # use the default script which is equivalent to the following
# - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
# - julia -e 'Pkg.clone(pwd()); Pkg.build("Hungarian"); Pkg.test("Hungarian"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("Hungarian")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("Hungarian")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
