name = "Hungarian"
uuid = "e91730f6-4275-51fb-a7a0-7064cfbd3b39"
authors = ["Yupei Qi <qiyupei@gmail.com>"]
version = "0.7.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1.0.0"

[extras]
Munkres = "4cefb923-2b6f-58c4-9e65-6821f26b7b51"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DelimitedFiles", "Munkres"]
